name: Deploy Multi-Env

on:
  push:
    # O deploy acontece quando código entra nessas branches
    branches:
      - main
      - develop
      - 'release/**' # Qualquer branch que comece com release/ (ex: release/v1.0)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      # LÓGICA DE SELEÇÃO DE AMBIENTE
      - name: Determine Target Stack
        id: target
        run: |
          # Se for a branch MAIN -> PROD
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "STACK_NAME=CookieAdmin-Prod" >> $GITHUB_ENV
            echo "Deploying to PRODUCTION"
          
          # Se for a branch DEVELOP -> DEV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "STACK_NAME=CookieAdmin-Dev" >> $GITHUB_ENV
            echo "Deploying to DEVELOPMENT"
          
          # Se for branch RELEASE -> STAGING
          elif [[ "${{ github.ref }}" == *"release/"* ]]; then
            echo "STACK_NAME=CookieAdmin-Staging" >> $GITHUB_ENV
            echo "Deploying to STAGING (Homolog)"
            
          else
            echo "Branch desconhecida para deploy automático."
            exit 1
          fi

      - name: CDK Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: cdk deploy ${{ env.STACK_NAME }} --require-approval never