name: Deploy Infrastructure

on:
  push:
    branches:
      - develop        # Deploy em DEV
      - 'release/*'    # Deploy em HOMOLOG
      - main           # Deploy em PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Permissões para ler o código e (opcional) usar OIDC
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js (CDK dependency)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK Global
        run: npm install -g aws-cdk

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 1. Instala dependências da INFRAESTRUTURA (CDK, Boto3 para o script de deploy)
      - name: Install CDK App Dependencies
        run: |
          pip install -r requirements.txt

      # 2. CORREÇÃO DO ERRO: Instala dependências da LAMBDA dentro da pasta src/
      # Isso garante que o Pydantic vá junto com o código no zip final
      - name: Install Lambda Dependencies (Vendorize)
        run: |
          echo "Instalando dependências da Lambda em src/..."
          pip install -r src/requirements.txt -t src/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Lógica para definir se é Dev, Homol ou Prod
      - name: Determine Environment
        id: env-selector
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV_TAG=prod" >> $GITHUB_ENV
            echo "Deploying to PRODUCTION"
          elif [[ "${{ github.ref }}" == *"release/"* ]]; then
            echo "ENV_TAG=homol" >> $GITHUB_ENV
            echo "Deploying to HOMOLOGATION"
          else
            echo "ENV_TAG=dev" >> $GITHUB_ENV
            echo "Deploying to DEVELOPMENT"
          fi

      # 4. O Deploy final
      - name: CDK Deploy
        run: |
          # A flag -c config=... passa o ambiente para o app.py
          cdk deploy --require-approval never -c config=${{ env.ENV_TAG }}